{% set name = "uont" %}
{% set data = load_file_regex(load_file=RECIPE_DIR + "/../src/uont/__init__.py", regex_pattern="__version__\\s*=\\s*['\"]([^'\"]+)['\"]") %}
{% set version = data.group(1) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  skip: true  # [ not linux ]
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =3.12
    - pip
    - flit-core >=3.11,<4
  run:
  - autocycler =0.7.0
  - chopper =0.13.0
  - dnaapler =1.4.0
  - filtlong =0.3.1
  - flye =2.9.6
  - joblib 
  - lrge =0.3.0
  - medaka =2.2.2
  - miniasm =0.3
  - minipolish =0.2.1
  - myloasm =0.6.0
  - nanoplot =1.47.1
  - nextdenovo =2.5.2
  - nextpolish =1.4.1
  - numpy 
  - openpyxl 
  - pandas 
  - pigz
  - plassembler =1.8.3
  - pysam =0.24.0
  - python >=3.10
  - pyyaml
  - raven-assembler =1.8.3
  - rich
  - rich-argparse
  - seqkit =2.13.0
  - tqdm

test:
  imports:
    - uont
  commands:
    - uont --help

about:
  home: https://jodyphelan.github.io/uont/
  license: MIT
  license_family: MIT
  summary: Pipeline for polishing Oxford Nanopore reads into assemblies.
  description: |
    uont provides CLI workflows and helper processes that filter, downsample,
    assemble, and polish Oxford Nanopore Technologies sequencing reads into
    high-quality assemblies using tools like chopper, autocycler, filtlong,
    flye, and medaka.
  dev_url: https://jodyphelan.github.io/uont/

extra:
  recipe-maintainers:
    - jodyphelan